# -*- coding: utf-8 -*-
"""sales_data_cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gzQM43rfdSKZtV6HLRL-X_SKAPgvzAK-
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import drive
drive.mount('/content/drive')

path = "/content/drive/MyDrive/Sales_Performance_KPI_Dashboard/Data/Sales data - Superstore.csv"
try:
    df = pd.read_csv(path, encoding='latin1')
except UnicodeDecodeError:
    try:
        df = pd.read_csv(path, encoding='ISO-8859-1')
    except Exception as e:
        print(f"Could not decode the file with latin1 or ISO-8859-1 encoding: {e}")
except FileNotFoundError:
    print(f"Error: File not found at {path}. Please check the path.")
except Exception as e:
    print(f"An error occurred: {e}")

if 'df' in locals():
    display(df.head())

df.head(10)

df.columns

df.info()

df.describe()

# Drop duplicates if any
df.drop_duplicates(inplace=True)

# Handle missing numeric values
df.fillna(0, inplace=True)

df['Order Date'] = pd.to_datetime(df['Order Date'], errors='coerce')
df['Ship Date'] = pd.to_datetime(df['Ship Date'], errors='coerce')

# Remove duplicates
df.drop_duplicates(inplace=True)

# Fill any missing numeric values
df.fillna(0, inplace=True)

# Verify
df.isnull().sum()

# Total Sales is already given as 'Sales', but we can ensure consistency
df.rename(columns={'Sales': 'TotalSales'}, inplace=True)

# Profit Margin Calculation
df['ProfitMargin'] = np.where(df['TotalSales'] > 0, (df['Profit'] / df['TotalSales']) * 100, 0)

# Average Order Value (AOV)
df['AOV'] = df.groupby('Order ID')['TotalSales'].transform('mean')

df.to_csv("clean_superstore_sales.csv", index=False)
from google.colab import files
files.download("clean_superstore_sales.csv")